spring:
  profiles:
    active:
    - local

---



spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:\\Users\\l2-evening\\Documents\\work10\\lcomputerstudy1\\src\\main\\webapp\\WEB-INF\\views
      max-file-size: 100MB
      max-request-size: 100MB

  profiles:
  - local
  
  mvc: 
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
  
  datasource:
    url: jdbc:mysql://localhost:3306/ex?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  session:
    jdbc:
      initialize-schema: always
      
  devtools:    livereload:      enabled: true
      
server:
 port: 8080
 tomcat:
    file-encoding: UTF-8
    
 servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
       
    jsp:
      init-parameters: 
        development: true 
    session: 
      timeout: 7200
 error:
      whitelabel:
        enabled: false 
mybatis:
  type-aliases-package: com.lcomputerstudy1.example.domain
  mapper-locations: mapper/**/*.xml
  
logging:
  config: classpath:logback-spring.xml